services:
  postgres:
    image: postgres:15
    container_name: postgres_dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: password
      POSTGRES_PASSWORD: veterinaryclinic_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: