version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: veterinaryclinic_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: